name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy To Server (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: github-workflow-artifacts
      - name: Install NPM modules, copy proper production environment, and compile typescript
        uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - run: cd github-workflow-artifacts/backend && npm install
      - run: cp github-workflow-artifacts/backend/src/env/.env.production.json github-workflow-artifacts/backend/src/env/.env.json
      - run: cd github-workflow-artifacts/backend && tsc --build tsconfig.json
      - name: Copy build directory to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "github-workflow-artifacts//backend/build"
          target: "/home/pi/projects/stock-jarvis"
          overwrite: true
      - name: Restart (or start when restart fails) node forever on the server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/pi/.profile
            cd "/home/pi/projects/stock-jarvis/github-workflow-artifacts/build/backend"
            forever restart index.js || forever start index.js && echo 'Forever successfully running!'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Build complete! Latest commit message on build