name: Deploy To Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone on server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/pi/projects/stock-jarvis
            git pull
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          args: "-vvv"