name: Deploy To Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Install NPM modules and compile typescript
        uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - run: npm install
      - run: tsc
      - name: Copy build directory to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "main/build"
          target: ${{ secrets.BUILD_DIRECTORY }}
      - name: Restart node forever on the server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/pi/.profile
            cd ${{ secrets.DIRECTORY }}
            forever restart build/index.js
            echo 'Forever successfully restarted!'
