name: Deploy To Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM modules and build for production
      - uses: actions/checkout@master
        run: |
          npm install
          cp src/env/.env.production.json src/env/.env.json
          tsc
      - name: Pull this repository to the server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/pi/.profile
            cd ${{ secrets.DIRECTORY }}
            git pull
            forever restart build/index.js
            echo 'Forever successfully restarted!'
